server:
  port: 8081

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

jwt:
  key: ENC(z3TJ+ttlygJqK7LFC699KrE4WQ0kafXO01WE1aToFugIAa8g6FXAsmlsvoyIgLZeaLjDtw5gNtUTjtFSoiSIV5VcaE5iX7Ap3PKGtzdqfq/DFw5Ne3f24WSLYRq7m3bEyAYb8jZ87aorxZnw5Dty2g==)
  expiration: 604800000 # 7 days

refresh-token:
  expiration: 30 # 30 days

spring:
  profiles:
    active: dev

  application:
    name: user-service

  liquibase:
    change-log: classpath:liquibase/master.yml

  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6380
      password: algofusion-tb-redis
      ssl:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
